### PR TITLE
make pacli-simple an optdepend

### PR DESCRIPTION
**Pull request by excalibur1234**
pacli-simple works as well as pacli and it does not require any changes in mhwd-tui itself.

please add this.

### CODE REVIEW

**Comment by Chrysostomus** [comment]
Sure. Btw, maybe you could add provides=("pacli")  to pacli-simple? That way it could be used with bmenu too.

**Comment by Chrysostomus** [comment]
Come to think of it, did you intend this for bmenu?

**Comment by excalibur1234** [comment]
thanks. 

i have added the provides=("pacli") to the PKGBUILD.
i will release a new version of pacli-simple called pacli-simple-git in the AUR the next couple of days. it looks like a pacli-simple package will be put into our repos by stefano, too.

if you want to use pacli-simple instead of pacli with bmenu (after it has been put into our repos), feel free to do it. i actually think that pacli is outdated and that pacli-simple is superior in almost every way (except translation support).

**Comment by Chrysostomus** [comment]
Yeah... I kinda phased out from pacli development after the code got so complex I couldn't read it anymore. Glad I could contribute with the fzf stuff before that. 

Btw, what would you think about adding a semi-automatic rollback function to pacli-simple?

**Comment by excalibur1234** [comment]
yes. it was the same for me and pacli development.

-------------------------------

do you want to use this for the rollback funtion?
https://github.com/giddie/bits-n-pieces/tree/master/pacman-undo
(i have not tested it yet, but i doubt it would work well with a text editor like nano)

or do you want to script it yourself (using downgrade)?
you could use fzf to list all packages lately upgraded (this informaiton is displayed in the pacman logs). and let the user mark the packages with TAB key. then, execute downgrade for all those packages.

i had to use the downgrade option of pacli-simple in tty already multiple times and the experience is not cumbersome. so, a more convenient way to downgrade multiple packages would be great.

should i give you write access for pacli-simple?
then, you can do the development directly there...

**Comment by Chrysostomus** [comment]
I'm more comfortable with sending pull requests. 

I was thinking something like:
1) parse pacman logs to get a list few of the last actions pacman performed.
2) try to revert that change by installing previous packages from cache with pacman -U or uninstalling offending package in case it was installation action. 

So like downgrade, but simpler and mass operation. Downgrade is already excellent tool for operating on single packages, but this would be for rolling back user actions. 

I need to try pacman undo, it might have useful code. But I was thinking more of fzf than text editor interface.

**Comment by excalibur1234** [comment]
you idea sounds actually better than mine.

i have just checked and there is no scriptable way to execute downgrade. this means using pacman -U or pacman -R in a script is a better idea.

i have also thought about using fzf as interface: the user can simply mark all last actions he wants to roll back and press ENTER. much more convenient than a text editor interface!

pacli-simple was just released in the manjaro repos and i have renamed the AUR package to pacli-simple-git. this means we can do the development of this new function/option in pacli-simple.
if you feel uncomfortable with that, fork it and give me contributor status on your fork. then, we can work together on it.
i have seen that you will be really busy in the future, so do not feel pressured. i will be really busy in the next couple of months, too.

**Comment by excalibur1234** [comment]
i have just written such an option. so, you do not have to do it anymore.
but you can still fork the pacli-simple repo and send pull requests with improvements...

**Pull request merged**
